### ISSUE TITLE
Vine Post ID

### ISSUE THREAD

**Issue by avnerho** [stuisme/VineSharp#3]
Hi,
I was trying to use the Post (long postID) of VineClient and noticed that the postID is somehow of type long. However when I enter a post page on vine i.e. : https://vine.co/v/eYgeYlYAOQv
the id looks like a string and not a number. 
what exactly is the post ID of type long, and how do I get it if I have a url of specific video like the example above??

**Comment by stuisme** [comment]
Good question, I did some googling and found an NPM package that can do this. VineSharp is open for contribution if you want to put in a PR to include this.

https://github.com/slang800/vine-id-to-url-segment
